### ISSUE TITLE
 undefined method `template' for class `Test::Unit::Assertions::AssertionMessage' (NameError)

### ISSUE THREAD

**Issue by shivareddy547** [Blazemeter/blazemeter-gem#2]
Hi,

I am using ruby 2.0.0,rails 3.2,After blazemeter-gem installation through gem file ,if i trying to restart the serever it s giving like below.
 undefined method `template' for class`Test::Unit::Assertions::AssertionMessage' (NameError)
from /home/developer/redmine-2.6.1-0/ruby/lib/ruby/gems/2.0.0/gems/blazemeter-0.5.3/lib/blazemeter/utils.rb:9:in `module:Assertions'

Please help me how to solve this..!

Thanks
Shivareddy.A

**Comment by tamerzg** [comment]
Hello, we fixed this in latest commit.
